// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PBz6G5ieuMOt6Yuj5Ey6DWs6ulbQozg',
    appId: '1:473437165434:web:07b78efec3f883d381a8c3',
    messagingSenderId: '473437165434',
    projectId: 'devtodo-c0c65',
    authDomain: 'devtodo-c0c65.firebaseapp.com',
    storageBucket: 'devtodo-c0c65.appspot.com',
    measurementId: 'G-C81XER5CMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnuOrfu7Y3G9JYmTF7y3ZXl9Mtr59irI',
    appId: '1:473437165434:android:e2628dc80ddc3a7a81a8c3',
    messagingSenderId: '473437165434',
    projectId: 'devtodo-c0c65',
    storageBucket: 'devtodo-c0c65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgEmynRNBxQrpflNdXlCLozyjG5ORwNVU',
    appId: '1:473437165434:ios:372028a2dc78698281a8c3',
    messagingSenderId: '473437165434',
    projectId: 'devtodo-c0c65',
    storageBucket: 'devtodo-c0c65.appspot.com',
    iosClientId: '473437165434-c5lkest9fghscl0l06fpieh4n71lceg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.devtodo',
  );
}
